---
version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: ./build/docker/app/Dockerfile
      target: local
    ports:
      - ${DOCKER_COMPOSE_PORT_APP}:80
    volumes:
      - ./app:/var/www:cached
    working_dir: /var/www
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - ENVIRONMENT=local
      - COMPOSER_MEMORY_LIMIT=-1

  test:
    build:
      context: .
      dockerfile: ./build/docker/app/Dockerfile
      target: local
    volumes:
      - ./app:/var/www:cached
    working_dir: /var/www
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - ENVIRONMENT=test
      - DATABASE_NAME=db_test

  db:
    build: ./build/docker/postgres
    ports:
      - ${DOCKER_COMPOSE_PORT_DB}:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db

  sentinel:
    build: build/docker/sentinel
    ports:
      - ${DOCKER_COMPOSE_PORT_REDIS}:6379
    depends_on:
      - master
      - slave
    links:
      - master:redis_master
      - slave
    environment:
      - SENTINEL_SERVICE_NAME=redis

  master:
    image: redis:3.2
    command: redis-server # --requirepass local
    volumes:
      - ./var/data/redis:/data

  slave:
    image: redis:3.2
    command: redis-server --slaveof redis_master 6379 # --requirepass local --masterauth local
    depends_on:
      - master
    links:
      - master:redis_master

volumes:
  db-data:
