---
easy_admin:
  design:
    templates:
      layout: 'layout.html.twig'
      menu: 'menu.html.twig'
    menu:
      - {entity: 'Project', permission: 'ROLE_GUEST'}
      - {entity: 'User', permission: 'ROLE_GUEST'}
