---
App\Domain\Entity\Project\Project:
  type: entity
  table: project
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 256
